// src/lib/content/index.ts – Admin project
export const content = {
  // ============================================
  // AUTHENTICATION
  // ============================================
  auth: {
    poweredBy: {
      text: "Powered by Ocean Intuition",
    },
    login: {
      title: "Login to TraviatorJets",
      subtitle: "Admin Dashboard",
      emailLabel: "Email",
      emailPlaceholder: "admin@traviatorjets.com",
      passwordLabel: "Password",
      passwordPlaceholder: "••••••••",
      submitButton: "Sign in",
      forgotPasswordLink: "Forgot your password?",
      // No signup for admin
    },
    forgotPassword: {
      title: "Reset your password",
      subtitle: "Enter your email to receive a reset link",
      emailLabel: "Email",
      emailPlaceholder: "admin@traviatorjets.com",
      submitButton: "Send reset link",
      backToLogin: "Back to login",
      successMessage: "Check your email for a reset link.",
    },
    resetPassword: {
      title: "Set new password",
      subtitle: "Choose a strong password for your account",
      newPasswordLabel: "New Password",
      newPasswordPlaceholder: "••••••••",
      confirmPasswordLabel: "Confirm Password",
      confirmPasswordPlaceholder: "••••••••",
      submitButton: "Reset password",
      successMessage: "Password reset successfully",
    },
    invite: {
      title: "Accept Invitation",
      subtitle: "Create your admin account",
      emailLabel: "Email",
      passwordLabel: "Password",
      passwordPlaceholder: "••••••••",
      confirmPasswordLabel: "Confirm Password",
      confirmPasswordPlaceholder: "••••••••",
      submitButton: "Accept invitation",
      validating: "Validating invitation...",
      errorInvalid: "Invalid or expired invitation",
      errorFailed: "Failed to validate invitation",
      successMessage: "Account created successfully",
    },
    toast: {
      loginSuccess: "Signed in successfully",
      loginError: "Failed to sign in",
      forgotSuccess: "Password reset link sent to your email",
      forgotError: "Failed to send reset email",
      resetSuccess: "Password reset successfully",
      resetError: "Failed to reset password",
      inviteSuccess: "Account created successfully",
      inviteError: "Failed to accept invitation",
    },
  },

  // ============================================
  // DASHBOARD (shared layout)
  // ============================================
  dashboard: {
    sidebar: {
      header: {
        logo: "/logo.svg",
        title: "Traviator Jets",
        subtitle: "Premium Aviation",
      },

      mainLinks: [
        { href: "/", label: "Dashboard", icon: "LayoutDashboard", managerOnly: false },
        { href: "/airports", label: "Airports", icon: "PlaneLanding", managerOnly: false },
        { href: "/requests", label: "Requests", icon: "FileText", managerOnly: false },
        { href: "/empty-legs", label: "Empty Legs", icon: "TicketsPlane", managerOnly: false },
        { href: "/aircraft-types", label: "Aircraft Types", icon: "Plane", managerOnly: false },
        { href: "/aircraft-listings", label: "Aircraft Listings", icon: "ShoppingCart", managerOnly: false },
        { href: "/analytics", label: "Analytics", icon: "BarChart", managerOnly: true },
        { href: "/staffs", label: "Staff Management", icon: "Users", managerOnly: true },
      ],

      requestsTitle: "Your Requests",
      noRequests: "No assigned requests.",
      moreButton: "More",
      maxRequests: 4,
    },
    // ============================================
    // TOP BAR CONFIG
    // ============================================
    topBar: {
      routes: {
        "/": "Dashboard",
        "/airports": "Airport Management",
        "/requests": "Request Management",
        "/requests/[id]": "Chat Room",
        "/empty-legs": "Empty Legs Management",
        "/aircraft-types": "Aircraft Types Management",
        "/aircraft-listings": "Aircraft Listings Management",
        "/staffs": "Staff Management",
        "/profile": "My Profile",
        "/settings": "Settings",
        "/analytics": "Analytics",
      } as Record<string, string>,
      profileMenu: [
        {
          key: "profile",
          label: "Profile",
          href: "/profile",
          managerOnly: false,
        },
        {
          key: "settings",
          label: "Settings",
          href: "/settings",
          managerOnly: false,
        },
        {
          key: "logout",
          label: "Logout",
          href: null,
          managerOnly: false,
        },
      ],
    },
  },

  // ============================================
  // PAGES (CRUD labels, etc.)
  // ============================================
  pages: {
    overview: {
      title: "Dashboard Overview",
      cards: {
        requests: {
          title: "Requests",
          assigned: "Assigned to You",
          unassigned: "Unassigned",
        },
        emptyLegs: {
          title: "Active Empty Legs",
          admin: "Admin Created",
          pexjet: "PEXJET Sourced",
        },
        invoices: {
          title: "Invoices",
          pending: "Pending",
          paid: "Paid",
        },
      },
      recentRequests: {
        title: "Recent Requests Assigned to You",
        noData: "No requests assigned to you yet.",
        columns: { type: "Type", user: "User", status: "Status", date: "Date" },
        dummyData: [
          {
            type: "charter",
            user: "John Doe",
            status: "confirmed",
            date: "2025-04-10",
          },
          {
            type: "empty_leg_inquiry",
            user: "Jane Smith",
            status: "open",
            date: "2025-04-09",
          },
          {
            type: "aircraft_inquiry",
            user: "Mike Johnson",
            status: "assigned",
            date: "2025-04-08",
          },
          {
            type: "charter",
            user: "Sarah Lee",
            status: "confirmed",
            date: "2025-04-07",
          },
          {
            type: "empty_leg_inquiry",
            user: "Robert Brown",
            status: "open",
            date: "2025-04-06",
          },
        ],
      },
      staffList: {
        title: "Team Members",
        noData: "No staff members found.",
        columns: { name: "Name", role: "Role" },
      },
    },
    airports: {
      title: "Airports Management",
      searchPlaceholder: "Search by ICAO, IATA, name, city, or country...",
      columns: {
        icao: "ICAO",
        iata: "IATA",
        name: "Airport Name",
        city: "City",
        country: "Country",
      },
      form: {
        title: "Airport Details",
        icao: "ICAO",
        iata: "IATA",
        name: "Airport Name",
        city: "City",
        country: "Country",
        latitude: "Latitude",
        longitude: "Longitude",
      },
      noResults: "No airports found.",
      pagination: {
        previous: "Previous",
        next: "Next",
      },
    },
    aircraftTypes: {
      title: "Aircraft Types",
      addButton: "Aircraft Type",
      createButton: "Create Aircraft Type",
      editButton: "Edit",
      deleteButton: "Delete",
      confirmDelete: "Are you sure you want to delete this aircraft type? This action cannot be undone.",
      columns: {
        name: "Name",
        manufacturer: "Manufacturer",
        class: "Class",
        range: "Range (km)",
        pax: "Pax",
        speed: "Speed (kt)",
      },
      form: {
        name: "Name",
        manufacturer: "Manufacturer",
        createTitle: "Create Aircraft Type",
        editTitle: "Edit Aircraft Type",
        class: "Aircraft Class",
        range: "Max Range (km)",
        pax: "Max Passengers",
        speed: "Cruise Speed (knots)",
        cabinHeight: "Cabin Height (m)",
        cabinLength: "Cabin Length (m)",
        cabinWidth: "Cabin Width (m)",
        luggageVolume: "Luggage Volume (m³)",
        description: "Description",
        namePlaceholder: "e.g., Cessna Citation CJ1",
        manufacturerPlaceholder: "e.g., Cessna",
        rangePlaceholder: "3111",
        paxPlaceholder: "5",
        speedPlaceholder: "400",
        cabinHeightPlaceholder: "1.45",
        cabinLengthPlaceholder: "3.35",
        cabinWidthPlaceholder: "1.47",
        luggageVolumePlaceholder: "1.56",
        descriptionPlaceholder: "Optional description...",
        selectClassPlaceholder: "Select class",
      },
      toast: {
        created: "Aircraft type created successfully",
        updated: "Aircraft type updated successfully",
        deleted: "Aircraft type deleted successfully",
        error: "Operation failed",
      },
    },
    aircraftListings: {
      title: "Aircraft Listings",
      addButton: "Add Listing",
      columns: {
        title: "Title",
        serialNumber: "Serial Number",
        aircraftType: "Aircraft Type",
        year: "Year",
        status: "Status",
      },
      form: {
        createTitle: "Create Aircraft Listing",
        editTitle: "Edit Aircraft Listing",
        title: "Title",
        titlePlaceholder: "Enter listing title",
        description: "Description",
        descriptionPlaceholder: "Detailed description...",
        aircraftType: "Aircraft Type",
        selectTypePlaceholder: "Select aircraft type",
        serialNumber: "Serial Number",
        serialNumberPlaceholder: "e.g., SN-12345",
        year: "Year",
        yearPlaceholder: "Manufacture year",
        cabinPlanImage: "Cabin Plan",
        cabinPlanImageHint: "Upload cabin layout image",
        listingSections: "Aircraft Specifications",
        listingSectionsHint: "Add sections with title and list items",
        images: "Images",
        imagesHint: "Upload up to 10 images",
        documents: "Documents",
        documentsHint: "Upload spec sheets, manuals, etc.",
        status: "Status",
        statusActive: "Active",
        statusSold: "Sold",
        statusInactive: "Inactive",
      },
      toast: {
        created: "Listing created successfully",
        updated: "Listing updated successfully",
        deleted: "Listing deleted successfully",
        error: "An error occurred",
      },
      confirmDelete: "Are you sure you want to delete this listing? This action cannot be undone.",
    },
    emptyLegs: {
      title: "Empty Legs",
      addButton: "Add Empty Leg",
      columns: {
        from: "From",
        to: "To",
        departure: "Departure",
        aircraft: "Aircraft",
        seats: "Seats",
        price: "Price",
        source: "Source",
      },
      form: {
        createTitle: "Add Empty Leg",
        editTitle: "Edit Empty Leg",
        depAirport: "Departure Airport",
        depAirportPlaceholder: "Search departure airport...",
        arrAirport: "Arrival Airport",
        arrAirportPlaceholder: "Search arrival airport...",
        departureTime: "Departure Time",
        aircraftName: "Aircraft Name",
        aircraftCategory: "Category",
        maxPax: "Max PAX",
        availableSeats: "Available Seats",
        totalSeats: "Total Seats",
        price: "Price",
        currency: "Currency",
        priceType: "Price Type",
        fixed: "Fixed",
        contact: "Contact",
        aircraftType: "Aircraft Type",
        aircraftTypePlaceholder: "Select aircraft type",
        comment: "Comment",
        commentPlaceholder: "Additional notes...",
        destinationImageUrl: "Destination Image URL",
        destinationImageUrlPlaceholder: "https://example.com/image.jpg",
        destinationDescription: "Destination Description",
        destinationDescriptionPlaceholder: "Brief description of the destination...",
      },
      toast: {
        created: "Empty leg created successfully",
        updated: "Empty leg updated successfully",
        deleted: "Empty leg deleted successfully",
        error: "Something went wrong",
      },
      confirmDelete: "Are you sure you want to delete this empty leg? This cannot be undone.",
    },
    staff: {
      title: "Staff",
      addButton: "Invite Staff",
      columns: {
        name: "Name",
        username: "Username",
        role: "Role",
        status: "Status",
      },
      form: {
        inviteTitle: "Invite Staff",
        changeRoleTitle: "Change Role",
        email: "Email",
        emailPlaceholder: "colleague@example.com",
        role: "Role",
        sendInvite: "Send Invite",
        updateRole: "Update Role",
      },
      toast: {
        inviteSent: "Invitation sent!",
        roleUpdated: "Role updated.",
        deleted: "Staff member removed.",
        error: "Something went wrong.",
      },
      confirmDelete: "Are you sure you want to remove this staff member? This action cannot be undone.",
    },
    profile: {
      title: "Profile",
      subtitle: "Manage your personal information and how others see you.",
      tabs: {
        profile: "Profile",
        accounts: "Security",
      },
      form: {
        fullName: "Full name",
        username: "Username",
        email: "Email address",
        phone: "Phone number",
        saveChanges: "Save changes",
        cancel: "Cancel",
        profileUpdated: "Profile updated successfully",
        usernameTaken: "This username is already taken",
        currentPassword: "Current password",
        newPassword: "New password",
        confirmPassword: "Confirm new password",
        updatePassword: "Update password",
        passwordUpdated: "Password updated successfully",
        changePasswordSubtitle: "Change your password to keep your account secure.",
        // Validation messages (keys used in schemas)
        fullNameMin: "Full name must be at least 2 characters",
        fullNameMax: "Full name is too long",
        usernameMin: "Username must be at least 3 characters",
        usernameMax: "Username is too long",
        usernameInvalidChars: "Only letters, numbers and underscores allowed",
        phoneInvalid: "Invalid phone number",
        currentRequired: "Current password is required",
        newMinLength: "Password must be at least 6 characters",
        confirmRequired: "Please confirm your new password",
        passwordMismatch: "Passwords do not match",
        currentIncorrect: "Current password is incorrect",
      },
    },
    requests: {
      unassigned: {
        title: "Unassigned Requests",
        empty: "No unassigned requests",
        claim: "Claim",
      },
      assigned: {
        title: "Assigned to Me",
        active: "Active",
        archived: "Archived",
        empty: "No assigned requests",
      },
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your application preferences and session.",
      tab: "General",

      // General tab sections
      theme: {
        label: "Theme",
        description: "Switch between light and dark mode.",
        switchedToLight: "Switched to light mode",
        switchedToDark: "Switched to dark mode",
      },
      logout: {
        label: "Logout",
        description: "Securely sign out of your account.",
        button: "Logout",
        success: "Logged out successfully",
      },
    },
    requestDetail: {
      header: {
        viewDetails: "View Details",
        closeRequest: "Close Request",
      },
      closeConfirmation: {
        title: "Close Request",
        description: "Are you sure you want to close this request? This action cannot be undone.",
        cancel: "Cancel",
        confirm: "Close Request",
      },
      detailsDialog: {
        title: "Request Details",
        saveChanges: "Save Changes",
        cancel: "Cancel",
      },
      chat: {
        input: {
          placeholder: "Type a message...",
          send: "Sent",
          uploadInvoice: "Upload Invoice",
          uploadConfirmation: "Upload Confirmation",
          attachFile: "Attach file",
          invoiceNumber: "Invoice Number",
          invoiceNumberPlaceholder: "e.g., INV-2024-001",
          invoiceUploaded: "Invoice uploaded",
          confirmationUploaded: "Confirmation uploaded",
          uploadFailed: "Upload failed",
        },
      },
    },
    analytics: {
      sync: {
        title: "External Empty Leg Sync",
        description: "Sync external data into the platform database.",
        syncing: "Syncing...",
        syncButton: "Sync",
        clearButton: "Clear",
        clearConfirm: "This will permanently delete all PexJet empty legs. Are you sure?",
        syncSuccess: "sync completed successfully",
        syncFailed: "Sync failed",
        clearSuccess: "All data cleared",
        clearFailed: "Clear failed",
        synced: "Synced",
        skipped: "Skipped",
        failed: "Failed",
        oldDataCleanup: "Old Data Cleanup",
        yes: "Yes",
        no: "No",
      },
      stats: {
        totalUsers: "Total Users",
        totalAdmins: "Total Admins",
      },
      adminPerformance: {
        title: "Admin Performance",
        name: "Name",
        totalRequests: "Total Requests",
        closedWithInvoice: "Closed (Confirmed)",
        closedWithoutInvoice: "Closed (Unconfirmed)",
      },
      monthlyRequests: {
        title: "Monthly Requests",
      },
      typeBreakdown: {
        title: "Request Types",
      },
    },
    // Other pages follow the same pattern
  },

  layout: {
    title: "TraviatorJets Admin",
    description: "Admin dashboard for TraviatorJets – manage flights, requests, team, and analytics.",
    logo: "/logo.svg",
    favicon: "/logo.svg",
    ogImage: "/og-image.png",
  },
} as const;

export type Content = typeof content;
